services:
  - type: web
    name: flask-modular-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: postgres://user:password@host:port/dbname
